### ISSUE TITLE
Build error in reactive-feign-app

### ISSUE THREAD

**Issue by wenqiglantz** [ViniciusArnhold/spring-native-experiments#1]
Hi, I noticed a build error when I tried to build your `reactive-feign-app` using `./gradlew :reactive-feign-app:build`.  Detailed output as follows.  Just wondering if it's a known issue you are already aware?  I notice the latest Spring Native version, 0.12.1, deprecated AccessBits, but not sure what's the equivalent of AccessBits.FULL_REFLECTION.  Any advice on how to resolve this issue would be greatly appreciated.

**Type-safe dependency accessors is an incubating feature.

> Task :reactive-feign-app:compileJava FAILED
C:\DEV\GITHUB\RESOURCES\spring-native-experiments\reactive-feign-app\src\main\java\dev\viniciusarnhold\experiments\aot\app\ReactiveFeignApplication.java:24: error: incompatible types: int cannot be converted to TypeAccess
                @TypeHint(types = ReactiveFeignAutoConfiguration.class, access = AccessBits.FULL_REFLECTION)
                                                                                           ^
Note: C:\DEV\GITHUB\RESOURCES\spring-native-experiments\reactive-feign-app\src\main\java\dev\viniciusarnhold\experiments\aot\app\ReactiveFeignApplication.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error

FAILURE: Build failed with an exception.**

**Comment by ViniciusArnhold** [comment]
Hello, this repo was only for experiments with spring-native.
Spring cloud (feign) does not yet support aot compilation.
